// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: clientapi/api.proto

package clientapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateIKCertRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EkCert string `protobuf:"bytes,1,opt,name=ekCert,proto3" json:"ekCert,omitempty"`
	IkPub  string `protobuf:"bytes,2,opt,name=ikPub,proto3" json:"ikPub,omitempty"`
	IkName []byte `protobuf:"bytes,3,opt,name=ikName,proto3" json:"ikName,omitempty"`
}

func (x *CreateIKCertRequest) Reset() {
	*x = CreateIKCertRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientapi_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateIKCertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIKCertRequest) ProtoMessage() {}

func (x *CreateIKCertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clientapi_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIKCertRequest.ProtoReflect.Descriptor instead.
func (*CreateIKCertRequest) Descriptor() ([]byte, []int) {
	return file_clientapi_api_proto_rawDescGZIP(), []int{0}
}

func (x *CreateIKCertRequest) GetEkCert() string {
	if x != nil {
		return x.EkCert
	}
	return ""
}

func (x *CreateIKCertRequest) GetIkPub() string {
	if x != nil {
		return x.IkPub
	}
	return ""
}

func (x *CreateIKCertRequest) GetIkName() []byte {
	if x != nil {
		return x.IkName
	}
	return nil
}

type CreateIKCertReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EncryptedIC     []byte `protobuf:"bytes,1,opt,name=EncryptedIC,proto3" json:"EncryptedIC,omitempty"`
	CredBlob        []byte `protobuf:"bytes,2,opt,name=CredBlob,proto3" json:"CredBlob,omitempty"`
	EncryptedSecret []byte `protobuf:"bytes,3,opt,name=EncryptedSecret,proto3" json:"EncryptedSecret,omitempty"`
	EncryptAlg      string `protobuf:"bytes,4,opt,name=EncryptAlg,proto3" json:"EncryptAlg,omitempty"`
	EncryptParam    []byte `protobuf:"bytes,5,opt,name=EncryptParam,proto3" json:"EncryptParam,omitempty"`
}

func (x *CreateIKCertReply) Reset() {
	*x = CreateIKCertReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientapi_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateIKCertReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIKCertReply) ProtoMessage() {}

func (x *CreateIKCertReply) ProtoReflect() protoreflect.Message {
	mi := &file_clientapi_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIKCertReply.ProtoReflect.Descriptor instead.
func (*CreateIKCertReply) Descriptor() ([]byte, []int) {
	return file_clientapi_api_proto_rawDescGZIP(), []int{1}
}

func (x *CreateIKCertReply) GetEncryptedIC() []byte {
	if x != nil {
		return x.EncryptedIC
	}
	return nil
}

func (x *CreateIKCertReply) GetCredBlob() []byte {
	if x != nil {
		return x.CredBlob
	}
	return nil
}

func (x *CreateIKCertReply) GetEncryptedSecret() []byte {
	if x != nil {
		return x.EncryptedSecret
	}
	return nil
}

func (x *CreateIKCertReply) GetEncryptAlg() string {
	if x != nil {
		return x.EncryptAlg
	}
	return ""
}

func (x *CreateIKCertReply) GetEncryptParam() []byte {
	if x != nil {
		return x.EncryptParam
	}
	return nil
}

type RegisterClientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ic         *Cert       `protobuf:"bytes,1,opt,name=ic,proto3" json:"ic,omitempty"`
	ClientInfo *ClientInfo `protobuf:"bytes,2,opt,name=clientInfo,proto3" json:"clientInfo,omitempty"`
}

func (x *RegisterClientRequest) Reset() {
	*x = RegisterClientRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientapi_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterClientRequest) ProtoMessage() {}

func (x *RegisterClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clientapi_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterClientRequest.ProtoReflect.Descriptor instead.
func (*RegisterClientRequest) Descriptor() ([]byte, []int) {
	return file_clientapi_api_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterClientRequest) GetIc() *Cert {
	if x != nil {
		return x.Ic
	}
	return nil
}

func (x *RegisterClientRequest) GetClientInfo() *ClientInfo {
	if x != nil {
		return x.ClientInfo
	}
	return nil
}

type Cert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cert []byte `protobuf:"bytes,1,opt,name=cert,proto3" json:"cert,omitempty"`
}

func (x *Cert) Reset() {
	*x = Cert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientapi_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cert) ProtoMessage() {}

func (x *Cert) ProtoReflect() protoreflect.Message {
	mi := &file_clientapi_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cert.ProtoReflect.Descriptor instead.
func (*Cert) Descriptor() ([]byte, []int) {
	return file_clientapi_api_proto_rawDescGZIP(), []int{3}
}

func (x *Cert) GetCert() []byte {
	if x != nil {
		return x.Cert
	}
	return nil
}

type ClientInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientInfo string `protobuf:"bytes,1,opt,name=clientInfo,proto3" json:"clientInfo,omitempty"`
}

func (x *ClientInfo) Reset() {
	*x = ClientInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientapi_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfo) ProtoMessage() {}

func (x *ClientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_clientapi_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInfo.ProtoReflect.Descriptor instead.
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return file_clientapi_api_proto_rawDescGZIP(), []int{4}
}

func (x *ClientInfo) GetClientInfo() string {
	if x != nil {
		return x.ClientInfo
	}
	return ""
}

type RegisterClientReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId     int64         `protobuf:"varint,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	ClientConfig *ClientConfig `protobuf:"bytes,2,opt,name=clientConfig,proto3" json:"clientConfig,omitempty"`
}

func (x *RegisterClientReply) Reset() {
	*x = RegisterClientReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientapi_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterClientReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterClientReply) ProtoMessage() {}

func (x *RegisterClientReply) ProtoReflect() protoreflect.Message {
	mi := &file_clientapi_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterClientReply.ProtoReflect.Descriptor instead.
func (*RegisterClientReply) Descriptor() ([]byte, []int) {
	return file_clientapi_api_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterClientReply) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *RegisterClientReply) GetClientConfig() *ClientConfig {
	if x != nil {
		return x.ClientConfig
	}
	return nil
}

type ClientConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HbDurationSeconds    int64  `protobuf:"varint,1,opt,name=hbDurationSeconds,proto3" json:"hbDurationSeconds,omitempty"`
	TrustDurationSeconds int64  `protobuf:"varint,2,opt,name=trustDurationSeconds,proto3" json:"trustDurationSeconds,omitempty"`
	DigestAlgorithm      string `protobuf:"bytes,3,opt,name=digestAlgorithm,proto3" json:"digestAlgorithm,omitempty"`
}

func (x *ClientConfig) Reset() {
	*x = ClientConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientapi_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConfig) ProtoMessage() {}

func (x *ClientConfig) ProtoReflect() protoreflect.Message {
	mi := &file_clientapi_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConfig.ProtoReflect.Descriptor instead.
func (*ClientConfig) Descriptor() ([]byte, []int) {
	return file_clientapi_api_proto_rawDescGZIP(), []int{6}
}

func (x *ClientConfig) GetHbDurationSeconds() int64 {
	if x != nil {
		return x.HbDurationSeconds
	}
	return 0
}

func (x *ClientConfig) GetTrustDurationSeconds() int64 {
	if x != nil {
		return x.TrustDurationSeconds
	}
	return 0
}

func (x *ClientConfig) GetDigestAlgorithm() string {
	if x != nil {
		return x.DigestAlgorithm
	}
	return ""
}

type UnregisterClientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId int64 `protobuf:"varint,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
}

func (x *UnregisterClientRequest) Reset() {
	*x = UnregisterClientRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientapi_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnregisterClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterClientRequest) ProtoMessage() {}

func (x *UnregisterClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clientapi_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterClientRequest.ProtoReflect.Descriptor instead.
func (*UnregisterClientRequest) Descriptor() ([]byte, []int) {
	return file_clientapi_api_proto_rawDescGZIP(), []int{7}
}

func (x *UnregisterClientRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

type UnregisterClientReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *UnregisterClientReply) Reset() {
	*x = UnregisterClientReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientapi_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnregisterClientReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterClientReply) ProtoMessage() {}

func (x *UnregisterClientReply) ProtoReflect() protoreflect.Message {
	mi := &file_clientapi_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterClientReply.ProtoReflect.Descriptor instead.
func (*UnregisterClientReply) Descriptor() ([]byte, []int) {
	return file_clientapi_api_proto_rawDescGZIP(), []int{8}
}

func (x *UnregisterClientReply) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type SendHeartbeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId int64 `protobuf:"varint,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
}

func (x *SendHeartbeatRequest) Reset() {
	*x = SendHeartbeatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientapi_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendHeartbeatRequest) ProtoMessage() {}

func (x *SendHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clientapi_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*SendHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_clientapi_api_proto_rawDescGZIP(), []int{9}
}

func (x *SendHeartbeatRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

type GenerateEKCertRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EkPub []byte `protobuf:"bytes,1,opt,name=ekPub,proto3" json:"ekPub,omitempty"`
}

func (x *GenerateEKCertRequest) Reset() {
	*x = GenerateEKCertRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientapi_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateEKCertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateEKCertRequest) ProtoMessage() {}

func (x *GenerateEKCertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clientapi_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateEKCertRequest.ProtoReflect.Descriptor instead.
func (*GenerateEKCertRequest) Descriptor() ([]byte, []int) {
	return file_clientapi_api_proto_rawDescGZIP(), []int{10}
}

func (x *GenerateEKCertRequest) GetEkPub() []byte {
	if x != nil {
		return x.EkPub
	}
	return nil
}

type GenerateEKCertReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EkCert []byte `protobuf:"bytes,1,opt,name=ekCert,proto3" json:"ekCert,omitempty"`
}

func (x *GenerateEKCertReply) Reset() {
	*x = GenerateEKCertReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientapi_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateEKCertReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateEKCertReply) ProtoMessage() {}

func (x *GenerateEKCertReply) ProtoReflect() protoreflect.Message {
	mi := &file_clientapi_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateEKCertReply.ProtoReflect.Descriptor instead.
func (*GenerateEKCertReply) Descriptor() ([]byte, []int) {
	return file_clientapi_api_proto_rawDescGZIP(), []int{11}
}

func (x *GenerateEKCertReply) GetEkCert() []byte {
	if x != nil {
		return x.EkCert
	}
	return nil
}

type SendHeartbeatReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NextAction       uint64            `protobuf:"varint,1,opt,name=nextAction,proto3" json:"nextAction,omitempty"`
	ActionParameters *ActionParameters `protobuf:"bytes,2,opt,name=actionParameters,proto3" json:"actionParameters,omitempty"`
}

func (x *SendHeartbeatReply) Reset() {
	*x = SendHeartbeatReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientapi_api_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendHeartbeatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendHeartbeatReply) ProtoMessage() {}

func (x *SendHeartbeatReply) ProtoReflect() protoreflect.Message {
	mi := &file_clientapi_api_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendHeartbeatReply.ProtoReflect.Descriptor instead.
func (*SendHeartbeatReply) Descriptor() ([]byte, []int) {
	return file_clientapi_api_proto_rawDescGZIP(), []int{12}
}

func (x *SendHeartbeatReply) GetNextAction() uint64 {
	if x != nil {
		return x.NextAction
	}
	return 0
}

func (x *SendHeartbeatReply) GetActionParameters() *ActionParameters {
	if x != nil {
		return x.ActionParameters
	}
	return nil
}

type ActionParameters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nonce        uint64        `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ClientConfig *ClientConfig `protobuf:"bytes,2,opt,name=clientConfig,proto3" json:"clientConfig,omitempty"`
}

func (x *ActionParameters) Reset() {
	*x = ActionParameters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientapi_api_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionParameters) ProtoMessage() {}

func (x *ActionParameters) ProtoReflect() protoreflect.Message {
	mi := &file_clientapi_api_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionParameters.ProtoReflect.Descriptor instead.
func (*ActionParameters) Descriptor() ([]byte, []int) {
	return file_clientapi_api_proto_rawDescGZIP(), []int{13}
}

func (x *ActionParameters) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *ActionParameters) GetClientConfig() *ClientConfig {
	if x != nil {
		return x.ClientConfig
	}
	return nil
}

type SendReportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId    int64        `protobuf:"varint,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	TrustReport *TrustReport `protobuf:"bytes,2,opt,name=trustReport,proto3" json:"trustReport,omitempty"`
}

func (x *SendReportRequest) Reset() {
	*x = SendReportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientapi_api_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendReportRequest) ProtoMessage() {}

func (x *SendReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clientapi_api_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendReportRequest.ProtoReflect.Descriptor instead.
func (*SendReportRequest) Descriptor() ([]byte, []int) {
	return file_clientapi_api_proto_rawDescGZIP(), []int{14}
}

func (x *SendReportRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *SendReportRequest) GetTrustReport() *TrustReport {
	if x != nil {
		return x.TrustReport
	}
	return nil
}

type TrustReport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PcrInfo    *PcrInfo    `protobuf:"bytes,1,opt,name=pcrInfo,proto3" json:"pcrInfo,omitempty"`
	Manifest   []*Manifest `protobuf:"bytes,2,rep,name=manifest,proto3" json:"manifest,omitempty"`
	ClientId   int64       `protobuf:"varint,3,opt,name=clientId,proto3" json:"clientId,omitempty"`
	ClientInfo *ClientInfo `protobuf:"bytes,4,opt,name=clientInfo,proto3" json:"clientInfo,omitempty"`
}

func (x *TrustReport) Reset() {
	*x = TrustReport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientapi_api_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrustReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrustReport) ProtoMessage() {}

func (x *TrustReport) ProtoReflect() protoreflect.Message {
	mi := &file_clientapi_api_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrustReport.ProtoReflect.Descriptor instead.
func (*TrustReport) Descriptor() ([]byte, []int) {
	return file_clientapi_api_proto_rawDescGZIP(), []int{15}
}

func (x *TrustReport) GetPcrInfo() *PcrInfo {
	if x != nil {
		return x.PcrInfo
	}
	return nil
}

func (x *TrustReport) GetManifest() []*Manifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *TrustReport) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *TrustReport) GetClientInfo() *ClientInfo {
	if x != nil {
		return x.ClientInfo
	}
	return nil
}

type PcrInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PcrValues map[int32]string `protobuf:"bytes,1,rep,name=pcrValues,proto3" json:"pcrValues,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	PcrQuote  *PcrQuote        `protobuf:"bytes,2,opt,name=pcrQuote,proto3" json:"pcrQuote,omitempty"`
	Algorithm string           `protobuf:"bytes,3,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
}

func (x *PcrInfo) Reset() {
	*x = PcrInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientapi_api_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PcrInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PcrInfo) ProtoMessage() {}

func (x *PcrInfo) ProtoReflect() protoreflect.Message {
	mi := &file_clientapi_api_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PcrInfo.ProtoReflect.Descriptor instead.
func (*PcrInfo) Descriptor() ([]byte, []int) {
	return file_clientapi_api_proto_rawDescGZIP(), []int{16}
}

func (x *PcrInfo) GetPcrValues() map[int32]string {
	if x != nil {
		return x.PcrValues
	}
	return nil
}

func (x *PcrInfo) GetPcrQuote() *PcrQuote {
	if x != nil {
		return x.PcrQuote
	}
	return nil
}

func (x *PcrInfo) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

type PcrQuote struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Quoted    []byte `protobuf:"bytes,1,opt,name=quoted,proto3" json:"quoted,omitempty"`
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *PcrQuote) Reset() {
	*x = PcrQuote{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientapi_api_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PcrQuote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PcrQuote) ProtoMessage() {}

func (x *PcrQuote) ProtoReflect() protoreflect.Message {
	mi := &file_clientapi_api_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PcrQuote.ProtoReflect.Descriptor instead.
func (*PcrQuote) Descriptor() ([]byte, []int) {
	return file_clientapi_api_proto_rawDescGZIP(), []int{17}
}

func (x *PcrQuote) GetQuoted() []byte {
	if x != nil {
		return x.Quoted
	}
	return nil
}

func (x *PcrQuote) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type Manifest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Item []byte `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *Manifest) Reset() {
	*x = Manifest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientapi_api_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest) ProtoMessage() {}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_clientapi_api_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest.ProtoReflect.Descriptor instead.
func (*Manifest) Descriptor() ([]byte, []int) {
	return file_clientapi_api_proto_rawDescGZIP(), []int{18}
}

func (x *Manifest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Manifest) GetItem() []byte {
	if x != nil {
		return x.Item
	}
	return nil
}

type SendReportReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *SendReportReply) Reset() {
	*x = SendReportReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientapi_api_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendReportReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendReportReply) ProtoMessage() {}

func (x *SendReportReply) ProtoReflect() protoreflect.Message {
	mi := &file_clientapi_api_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendReportReply.ProtoReflect.Descriptor instead.
func (*SendReportReply) Descriptor() ([]byte, []int) {
	return file_clientapi_api_proto_rawDescGZIP(), []int{19}
}

func (x *SendReportReply) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

var File_clientapi_api_proto protoreflect.FileDescriptor

var file_clientapi_api_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5b, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49,
	0x4b, 0x43, 0x65, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x65, 0x6b, 0x43, 0x65, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x6b,
	0x43, 0x65, 0x72, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6b, 0x50, 0x75, 0x62, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6b, 0x50, 0x75, 0x62, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6b,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x69, 0x6b, 0x4e, 0x61,
	0x6d, 0x65, 0x22, 0xbf, 0x01, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x4b, 0x43,
	0x65, 0x72, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x45, 0x6e, 0x63, 0x72,
	0x79, 0x70, 0x74, 0x65, 0x64, 0x49, 0x43, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x45,
	0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x49, 0x43, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x72,
	0x65, 0x64, 0x42, 0x6c, 0x6f, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x43, 0x72,
	0x65, 0x64, 0x42, 0x6c, 0x6f, 0x62, 0x12, 0x28, 0x0a, 0x0f, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70,
	0x74, 0x65, 0x64, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0f, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x12, 0x1e, 0x0a, 0x0a, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x41, 0x6c, 0x67, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x41, 0x6c, 0x67,
	0x12, 0x22, 0x0a, 0x0c, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x22, 0x5b, 0x0a, 0x15, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a,
	0x02, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x43, 0x65, 0x72, 0x74,
	0x52, 0x02, 0x69, 0x63, 0x12, 0x2b, 0x0a, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x22, 0x1a, 0x0a, 0x04, 0x43, 0x65, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x65, 0x72,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x63, 0x65, 0x72, 0x74, 0x22, 0x2c, 0x0a,
	0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x64, 0x0a, 0x13, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x31,
	0x0a, 0x0c, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x52, 0x0c, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x22, 0x9a, 0x01, 0x0a, 0x0c, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x2c, 0x0a, 0x11, 0x68, 0x62, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x68,
	0x62, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73,
	0x12, 0x32, 0x0a, 0x14, 0x74, 0x72, 0x75, 0x73, 0x74, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x14,
	0x74, 0x72, 0x75, 0x73, 0x74, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x63,
	0x6f, 0x6e, 0x64, 0x73, 0x12, 0x28, 0x0a, 0x0f, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x41, 0x6c,
	0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x64,
	0x69, 0x67, 0x65, 0x73, 0x74, 0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x22, 0x35,
	0x0a, 0x17, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x2f, 0x0a, 0x15, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x32, 0x0a, 0x14, 0x53, 0x65, 0x6e, 0x64, 0x48, 0x65,
	0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x2d, 0x0a, 0x15, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x45, 0x4b, 0x43, 0x65, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6b, 0x50, 0x75, 0x62, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x65, 0x6b, 0x50, 0x75, 0x62, 0x22, 0x2d, 0x0a, 0x13, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x45, 0x4b, 0x43, 0x65, 0x72, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x16, 0x0a, 0x06, 0x65, 0x6b, 0x43, 0x65, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x06, 0x65, 0x6b, 0x43, 0x65, 0x72, 0x74, 0x22, 0x73, 0x0a, 0x12, 0x53, 0x65, 0x6e, 0x64,
	0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1e,
	0x0a, 0x0a, 0x6e, 0x65, 0x78, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0a, 0x6e, 0x65, 0x78, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3d,
	0x0a, 0x10, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65,
	0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x52, 0x10, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x22, 0x5b, 0x0a,
	0x10, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x31, 0x0a, 0x0c, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x0c, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x5f, 0x0a, 0x11, 0x53, 0x65,
	0x6e, 0x64, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x0b, 0x74,
	0x72, 0x75, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x54, 0x72, 0x75, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x0b,
	0x74, 0x72, 0x75, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x22, 0xa1, 0x01, 0x0a, 0x0b,
	0x54, 0x72, 0x75, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x22, 0x0a, 0x07, 0x70,
	0x63, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x50,
	0x63, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x70, 0x63, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x25, 0x0a, 0x08, 0x6d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x09, 0x2e, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x52, 0x08, 0x6d, 0x61,
	0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x12, 0x2b, 0x0a, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x22,
	0xc3, 0x01, 0x0a, 0x07, 0x50, 0x63, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x35, 0x0a, 0x09, 0x70,
	0x63, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x50, 0x63, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x50, 0x63, 0x72, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x09, 0x70, 0x63, 0x72, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x12, 0x25, 0x0a, 0x08, 0x70, 0x63, 0x72, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x50, 0x63, 0x72, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x52,
	0x08, 0x70, 0x63, 0x72, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x6c, 0x67,
	0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x6c,
	0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x1a, 0x3c, 0x0a, 0x0e, 0x50, 0x63, 0x72, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x40, 0x0a, 0x08, 0x50, 0x63, 0x72, 0x51, 0x75, 0x6f, 0x74,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x06, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x32, 0x0a, 0x08, 0x4d, 0x61, 0x6e, 0x69, 0x66,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x22, 0x29, 0x0a, 0x0f, 0x53,
	0x65, 0x6e, 0x64, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x82, 0x03, 0x0a, 0x03, 0x52, 0x61, 0x73, 0x12, 0x3a,
	0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x4b, 0x43, 0x65, 0x72, 0x74, 0x12, 0x14,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x4b, 0x43, 0x65, 0x72, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x4b, 0x43,
	0x65, 0x72, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0e, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x45, 0x4b, 0x43, 0x65, 0x72, 0x74, 0x12, 0x16, 0x2e, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x45, 0x4b, 0x43, 0x65, 0x72, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x45,
	0x4b, 0x43, 0x65, 0x72, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0e,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x16,
	0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x46,
	0x0a, 0x10, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x12, 0x18, 0x2e, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x55,
	0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0d, 0x53, 0x65, 0x6e, 0x64, 0x48, 0x65,
	0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x15, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x48, 0x65,
	0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13,
	0x2e, 0x53, 0x65, 0x6e, 0x64, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x0a, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x12, 0x12, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x3b, 0x5a, 0x39, 0x67,
	0x69, 0x74, 0x65, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x65, 0x75, 0x6c,
	0x65, 0x72, 0x2f, 0x6b, 0x75, 0x6e, 0x70, 0x65, 0x6e, 0x67, 0x73, 0x65, 0x63, 0x6c, 0x2f, 0x61,
	0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x72, 0x61, 0x73, 0x2f, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_clientapi_api_proto_rawDescOnce sync.Once
	file_clientapi_api_proto_rawDescData = file_clientapi_api_proto_rawDesc
)

func file_clientapi_api_proto_rawDescGZIP() []byte {
	file_clientapi_api_proto_rawDescOnce.Do(func() {
		file_clientapi_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_clientapi_api_proto_rawDescData)
	})
	return file_clientapi_api_proto_rawDescData
}

var file_clientapi_api_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_clientapi_api_proto_goTypes = []interface{}{
	(*CreateIKCertRequest)(nil),     // 0: CreateIKCertRequest
	(*CreateIKCertReply)(nil),       // 1: CreateIKCertReply
	(*RegisterClientRequest)(nil),   // 2: RegisterClientRequest
	(*Cert)(nil),                    // 3: Cert
	(*ClientInfo)(nil),              // 4: ClientInfo
	(*RegisterClientReply)(nil),     // 5: RegisterClientReply
	(*ClientConfig)(nil),            // 6: ClientConfig
	(*UnregisterClientRequest)(nil), // 7: UnregisterClientRequest
	(*UnregisterClientReply)(nil),   // 8: UnregisterClientReply
	(*SendHeartbeatRequest)(nil),    // 9: SendHeartbeatRequest
	(*GenerateEKCertRequest)(nil),   // 10: GenerateEKCertRequest
	(*GenerateEKCertReply)(nil),     // 11: GenerateEKCertReply
	(*SendHeartbeatReply)(nil),      // 12: SendHeartbeatReply
	(*ActionParameters)(nil),        // 13: ActionParameters
	(*SendReportRequest)(nil),       // 14: SendReportRequest
	(*TrustReport)(nil),             // 15: TrustReport
	(*PcrInfo)(nil),                 // 16: PcrInfo
	(*PcrQuote)(nil),                // 17: PcrQuote
	(*Manifest)(nil),                // 18: Manifest
	(*SendReportReply)(nil),         // 19: SendReportReply
	nil,                             // 20: PcrInfo.PcrValuesEntry
}
var file_clientapi_api_proto_depIdxs = []int32{
	3,  // 0: RegisterClientRequest.ic:type_name -> Cert
	4,  // 1: RegisterClientRequest.clientInfo:type_name -> ClientInfo
	6,  // 2: RegisterClientReply.clientConfig:type_name -> ClientConfig
	13, // 3: SendHeartbeatReply.actionParameters:type_name -> ActionParameters
	6,  // 4: ActionParameters.clientConfig:type_name -> ClientConfig
	15, // 5: SendReportRequest.trustReport:type_name -> TrustReport
	16, // 6: TrustReport.pcrInfo:type_name -> PcrInfo
	18, // 7: TrustReport.manifest:type_name -> Manifest
	4,  // 8: TrustReport.clientInfo:type_name -> ClientInfo
	20, // 9: PcrInfo.pcrValues:type_name -> PcrInfo.PcrValuesEntry
	17, // 10: PcrInfo.pcrQuote:type_name -> PcrQuote
	0,  // 11: Ras.CreateIKCert:input_type -> CreateIKCertRequest
	10, // 12: Ras.GenerateEKCert:input_type -> GenerateEKCertRequest
	2,  // 13: Ras.RegisterClient:input_type -> RegisterClientRequest
	7,  // 14: Ras.UnregisterClient:input_type -> UnregisterClientRequest
	9,  // 15: Ras.SendHeartbeat:input_type -> SendHeartbeatRequest
	14, // 16: Ras.SendReport:input_type -> SendReportRequest
	1,  // 17: Ras.CreateIKCert:output_type -> CreateIKCertReply
	11, // 18: Ras.GenerateEKCert:output_type -> GenerateEKCertReply
	5,  // 19: Ras.RegisterClient:output_type -> RegisterClientReply
	8,  // 20: Ras.UnregisterClient:output_type -> UnregisterClientReply
	12, // 21: Ras.SendHeartbeat:output_type -> SendHeartbeatReply
	19, // 22: Ras.SendReport:output_type -> SendReportReply
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_clientapi_api_proto_init() }
func file_clientapi_api_proto_init() {
	if File_clientapi_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_clientapi_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateIKCertRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientapi_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateIKCertReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientapi_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterClientRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientapi_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientapi_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientapi_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterClientReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientapi_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientapi_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnregisterClientRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientapi_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnregisterClientReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientapi_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendHeartbeatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientapi_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateEKCertRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientapi_api_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateEKCertReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientapi_api_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendHeartbeatReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientapi_api_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionParameters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientapi_api_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendReportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientapi_api_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrustReport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientapi_api_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PcrInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientapi_api_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PcrQuote); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientapi_api_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Manifest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientapi_api_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendReportReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_clientapi_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clientapi_api_proto_goTypes,
		DependencyIndexes: file_clientapi_api_proto_depIdxs,
		MessageInfos:      file_clientapi_api_proto_msgTypes,
	}.Build()
	File_clientapi_api_proto = out.File
	file_clientapi_api_proto_rawDesc = nil
	file_clientapi_api_proto_goTypes = nil
	file_clientapi_api_proto_depIdxs = nil
}
