// Code generated by protoc-gen-go. DO NOT EDIT.
// source: clientapi/api.proto

package clientapi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateIKCertRequest struct {
	EkCert               string   `protobuf:"bytes,1,opt,name=ekCert,proto3" json:"ekCert,omitempty"`
	IkPub                string   `protobuf:"bytes,2,opt,name=ikPub,proto3" json:"ikPub,omitempty"`
	IkName               []byte   `protobuf:"bytes,3,opt,name=ikName,proto3" json:"ikName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateIKCertRequest) Reset()         { *m = CreateIKCertRequest{} }
func (m *CreateIKCertRequest) String() string { return proto.CompactTextString(m) }
func (*CreateIKCertRequest) ProtoMessage()    {}
func (*CreateIKCertRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_69f58a67dc46da5a, []int{0}
}

func (m *CreateIKCertRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateIKCertRequest.Unmarshal(m, b)
}
func (m *CreateIKCertRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateIKCertRequest.Marshal(b, m, deterministic)
}
func (m *CreateIKCertRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateIKCertRequest.Merge(m, src)
}
func (m *CreateIKCertRequest) XXX_Size() int {
	return xxx_messageInfo_CreateIKCertRequest.Size(m)
}
func (m *CreateIKCertRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateIKCertRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateIKCertRequest proto.InternalMessageInfo

func (m *CreateIKCertRequest) GetEkCert() string {
	if m != nil {
		return m.EkCert
	}
	return ""
}

func (m *CreateIKCertRequest) GetIkPub() string {
	if m != nil {
		return m.IkPub
	}
	return ""
}

func (m *CreateIKCertRequest) GetIkName() []byte {
	if m != nil {
		return m.IkName
	}
	return nil
}

type CreateIKCertReply struct {
	IcEncrypted          *CertEncrypted `protobuf:"bytes,1,opt,name=icEncrypted,proto3" json:"icEncrypted,omitempty"`
	Challenge            *Challenge     `protobuf:"bytes,2,opt,name=challenge,proto3" json:"challenge,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateIKCertReply) Reset()         { *m = CreateIKCertReply{} }
func (m *CreateIKCertReply) String() string { return proto.CompactTextString(m) }
func (*CreateIKCertReply) ProtoMessage()    {}
func (*CreateIKCertReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_69f58a67dc46da5a, []int{1}
}

func (m *CreateIKCertReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateIKCertReply.Unmarshal(m, b)
}
func (m *CreateIKCertReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateIKCertReply.Marshal(b, m, deterministic)
}
func (m *CreateIKCertReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateIKCertReply.Merge(m, src)
}
func (m *CreateIKCertReply) XXX_Size() int {
	return xxx_messageInfo_CreateIKCertReply.Size(m)
}
func (m *CreateIKCertReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateIKCertReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateIKCertReply proto.InternalMessageInfo

func (m *CreateIKCertReply) GetIcEncrypted() *CertEncrypted {
	if m != nil {
		return m.IcEncrypted
	}
	return nil
}

func (m *CreateIKCertReply) GetChallenge() *Challenge {
	if m != nil {
		return m.Challenge
	}
	return nil
}

type CertEncrypted struct {
	EncryptedIC          []byte   `protobuf:"bytes,1,opt,name=EncryptedIC,proto3" json:"EncryptedIC,omitempty"`
	IV                   []byte   `protobuf:"bytes,2,opt,name=IV,proto3" json:"IV,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CertEncrypted) Reset()         { *m = CertEncrypted{} }
func (m *CertEncrypted) String() string { return proto.CompactTextString(m) }
func (*CertEncrypted) ProtoMessage()    {}
func (*CertEncrypted) Descriptor() ([]byte, []int) {
	return fileDescriptor_69f58a67dc46da5a, []int{2}
}

func (m *CertEncrypted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CertEncrypted.Unmarshal(m, b)
}
func (m *CertEncrypted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CertEncrypted.Marshal(b, m, deterministic)
}
func (m *CertEncrypted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CertEncrypted.Merge(m, src)
}
func (m *CertEncrypted) XXX_Size() int {
	return xxx_messageInfo_CertEncrypted.Size(m)
}
func (m *CertEncrypted) XXX_DiscardUnknown() {
	xxx_messageInfo_CertEncrypted.DiscardUnknown(m)
}

var xxx_messageInfo_CertEncrypted proto.InternalMessageInfo

func (m *CertEncrypted) GetEncryptedIC() []byte {
	if m != nil {
		return m.EncryptedIC
	}
	return nil
}

func (m *CertEncrypted) GetIV() []byte {
	if m != nil {
		return m.IV
	}
	return nil
}

type Challenge struct {
	CredBlob             []byte   `protobuf:"bytes,1,opt,name=CredBlob,proto3" json:"CredBlob,omitempty"`
	EncryptedSecret      []byte   `protobuf:"bytes,2,opt,name=EncryptedSecret,proto3" json:"EncryptedSecret,omitempty"`
	EncryptAlg           string   `protobuf:"bytes,3,opt,name=EncryptAlg,proto3" json:"EncryptAlg,omitempty"`
	EncryptParam         []byte   `protobuf:"bytes,4,opt,name=EncryptParam,proto3" json:"EncryptParam,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Challenge) Reset()         { *m = Challenge{} }
func (m *Challenge) String() string { return proto.CompactTextString(m) }
func (*Challenge) ProtoMessage()    {}
func (*Challenge) Descriptor() ([]byte, []int) {
	return fileDescriptor_69f58a67dc46da5a, []int{3}
}

func (m *Challenge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Challenge.Unmarshal(m, b)
}
func (m *Challenge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Challenge.Marshal(b, m, deterministic)
}
func (m *Challenge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Challenge.Merge(m, src)
}
func (m *Challenge) XXX_Size() int {
	return xxx_messageInfo_Challenge.Size(m)
}
func (m *Challenge) XXX_DiscardUnknown() {
	xxx_messageInfo_Challenge.DiscardUnknown(m)
}

var xxx_messageInfo_Challenge proto.InternalMessageInfo

func (m *Challenge) GetCredBlob() []byte {
	if m != nil {
		return m.CredBlob
	}
	return nil
}

func (m *Challenge) GetEncryptedSecret() []byte {
	if m != nil {
		return m.EncryptedSecret
	}
	return nil
}

func (m *Challenge) GetEncryptAlg() string {
	if m != nil {
		return m.EncryptAlg
	}
	return ""
}

func (m *Challenge) GetEncryptParam() []byte {
	if m != nil {
		return m.EncryptParam
	}
	return nil
}

type RegisterClientRequest struct {
	Ic                   *Cert       `protobuf:"bytes,1,opt,name=ic,proto3" json:"ic,omitempty"`
	ClientInfo           *ClientInfo `protobuf:"bytes,2,opt,name=clientInfo,proto3" json:"clientInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RegisterClientRequest) Reset()         { *m = RegisterClientRequest{} }
func (m *RegisterClientRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterClientRequest) ProtoMessage()    {}
func (*RegisterClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_69f58a67dc46da5a, []int{4}
}

func (m *RegisterClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterClientRequest.Unmarshal(m, b)
}
func (m *RegisterClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterClientRequest.Marshal(b, m, deterministic)
}
func (m *RegisterClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterClientRequest.Merge(m, src)
}
func (m *RegisterClientRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterClientRequest.Size(m)
}
func (m *RegisterClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterClientRequest proto.InternalMessageInfo

func (m *RegisterClientRequest) GetIc() *Cert {
	if m != nil {
		return m.Ic
	}
	return nil
}

func (m *RegisterClientRequest) GetClientInfo() *ClientInfo {
	if m != nil {
		return m.ClientInfo
	}
	return nil
}

type Cert struct {
	Cert                 []byte   `protobuf:"bytes,1,opt,name=cert,proto3" json:"cert,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cert) Reset()         { *m = Cert{} }
func (m *Cert) String() string { return proto.CompactTextString(m) }
func (*Cert) ProtoMessage()    {}
func (*Cert) Descriptor() ([]byte, []int) {
	return fileDescriptor_69f58a67dc46da5a, []int{5}
}

func (m *Cert) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cert.Unmarshal(m, b)
}
func (m *Cert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cert.Marshal(b, m, deterministic)
}
func (m *Cert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cert.Merge(m, src)
}
func (m *Cert) XXX_Size() int {
	return xxx_messageInfo_Cert.Size(m)
}
func (m *Cert) XXX_DiscardUnknown() {
	xxx_messageInfo_Cert.DiscardUnknown(m)
}

var xxx_messageInfo_Cert proto.InternalMessageInfo

func (m *Cert) GetCert() []byte {
	if m != nil {
		return m.Cert
	}
	return nil
}

type ClientInfo struct {
	ClientInfo           string   `protobuf:"bytes,1,opt,name=clientInfo,proto3" json:"clientInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientInfo) Reset()         { *m = ClientInfo{} }
func (m *ClientInfo) String() string { return proto.CompactTextString(m) }
func (*ClientInfo) ProtoMessage()    {}
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_69f58a67dc46da5a, []int{6}
}

func (m *ClientInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientInfo.Unmarshal(m, b)
}
func (m *ClientInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientInfo.Marshal(b, m, deterministic)
}
func (m *ClientInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientInfo.Merge(m, src)
}
func (m *ClientInfo) XXX_Size() int {
	return xxx_messageInfo_ClientInfo.Size(m)
}
func (m *ClientInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ClientInfo proto.InternalMessageInfo

func (m *ClientInfo) GetClientInfo() string {
	if m != nil {
		return m.ClientInfo
	}
	return ""
}

type RegisterClientReply struct {
	ClientId             int64         `protobuf:"varint,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	ClientConfig         *ClientConfig `protobuf:"bytes,2,opt,name=clientConfig,proto3" json:"clientConfig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RegisterClientReply) Reset()         { *m = RegisterClientReply{} }
func (m *RegisterClientReply) String() string { return proto.CompactTextString(m) }
func (*RegisterClientReply) ProtoMessage()    {}
func (*RegisterClientReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_69f58a67dc46da5a, []int{7}
}

func (m *RegisterClientReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterClientReply.Unmarshal(m, b)
}
func (m *RegisterClientReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterClientReply.Marshal(b, m, deterministic)
}
func (m *RegisterClientReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterClientReply.Merge(m, src)
}
func (m *RegisterClientReply) XXX_Size() int {
	return xxx_messageInfo_RegisterClientReply.Size(m)
}
func (m *RegisterClientReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterClientReply.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterClientReply proto.InternalMessageInfo

func (m *RegisterClientReply) GetClientId() int64 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

func (m *RegisterClientReply) GetClientConfig() *ClientConfig {
	if m != nil {
		return m.ClientConfig
	}
	return nil
}

type ClientConfig struct {
	HbDurationSeconds    int64    `protobuf:"varint,1,opt,name=hbDurationSeconds,proto3" json:"hbDurationSeconds,omitempty"`
	TrustDurationSeconds int64    `protobuf:"varint,2,opt,name=trustDurationSeconds,proto3" json:"trustDurationSeconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientConfig) Reset()         { *m = ClientConfig{} }
func (m *ClientConfig) String() string { return proto.CompactTextString(m) }
func (*ClientConfig) ProtoMessage()    {}
func (*ClientConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_69f58a67dc46da5a, []int{8}
}

func (m *ClientConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientConfig.Unmarshal(m, b)
}
func (m *ClientConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientConfig.Marshal(b, m, deterministic)
}
func (m *ClientConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientConfig.Merge(m, src)
}
func (m *ClientConfig) XXX_Size() int {
	return xxx_messageInfo_ClientConfig.Size(m)
}
func (m *ClientConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ClientConfig proto.InternalMessageInfo

func (m *ClientConfig) GetHbDurationSeconds() int64 {
	if m != nil {
		return m.HbDurationSeconds
	}
	return 0
}

func (m *ClientConfig) GetTrustDurationSeconds() int64 {
	if m != nil {
		return m.TrustDurationSeconds
	}
	return 0
}

type UnregisterClientRequest struct {
	ClientId             int64    `protobuf:"varint,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnregisterClientRequest) Reset()         { *m = UnregisterClientRequest{} }
func (m *UnregisterClientRequest) String() string { return proto.CompactTextString(m) }
func (*UnregisterClientRequest) ProtoMessage()    {}
func (*UnregisterClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_69f58a67dc46da5a, []int{9}
}

func (m *UnregisterClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnregisterClientRequest.Unmarshal(m, b)
}
func (m *UnregisterClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnregisterClientRequest.Marshal(b, m, deterministic)
}
func (m *UnregisterClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnregisterClientRequest.Merge(m, src)
}
func (m *UnregisterClientRequest) XXX_Size() int {
	return xxx_messageInfo_UnregisterClientRequest.Size(m)
}
func (m *UnregisterClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnregisterClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnregisterClientRequest proto.InternalMessageInfo

func (m *UnregisterClientRequest) GetClientId() int64 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

type UnregisterClientReply struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnregisterClientReply) Reset()         { *m = UnregisterClientReply{} }
func (m *UnregisterClientReply) String() string { return proto.CompactTextString(m) }
func (*UnregisterClientReply) ProtoMessage()    {}
func (*UnregisterClientReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_69f58a67dc46da5a, []int{10}
}

func (m *UnregisterClientReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnregisterClientReply.Unmarshal(m, b)
}
func (m *UnregisterClientReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnregisterClientReply.Marshal(b, m, deterministic)
}
func (m *UnregisterClientReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnregisterClientReply.Merge(m, src)
}
func (m *UnregisterClientReply) XXX_Size() int {
	return xxx_messageInfo_UnregisterClientReply.Size(m)
}
func (m *UnregisterClientReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UnregisterClientReply.DiscardUnknown(m)
}

var xxx_messageInfo_UnregisterClientReply proto.InternalMessageInfo

func (m *UnregisterClientReply) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type SendHeartbeatRequest struct {
	ClientId             int64    `protobuf:"varint,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendHeartbeatRequest) Reset()         { *m = SendHeartbeatRequest{} }
func (m *SendHeartbeatRequest) String() string { return proto.CompactTextString(m) }
func (*SendHeartbeatRequest) ProtoMessage()    {}
func (*SendHeartbeatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_69f58a67dc46da5a, []int{11}
}

func (m *SendHeartbeatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendHeartbeatRequest.Unmarshal(m, b)
}
func (m *SendHeartbeatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendHeartbeatRequest.Marshal(b, m, deterministic)
}
func (m *SendHeartbeatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendHeartbeatRequest.Merge(m, src)
}
func (m *SendHeartbeatRequest) XXX_Size() int {
	return xxx_messageInfo_SendHeartbeatRequest.Size(m)
}
func (m *SendHeartbeatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendHeartbeatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendHeartbeatRequest proto.InternalMessageInfo

func (m *SendHeartbeatRequest) GetClientId() int64 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

type SendHeartbeatReply struct {
	NextAction           uint64            `protobuf:"varint,1,opt,name=nextAction,proto3" json:"nextAction,omitempty"`
	ActionParameters     *ActionParameters `protobuf:"bytes,2,opt,name=actionParameters,proto3" json:"actionParameters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SendHeartbeatReply) Reset()         { *m = SendHeartbeatReply{} }
func (m *SendHeartbeatReply) String() string { return proto.CompactTextString(m) }
func (*SendHeartbeatReply) ProtoMessage()    {}
func (*SendHeartbeatReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_69f58a67dc46da5a, []int{12}
}

func (m *SendHeartbeatReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendHeartbeatReply.Unmarshal(m, b)
}
func (m *SendHeartbeatReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendHeartbeatReply.Marshal(b, m, deterministic)
}
func (m *SendHeartbeatReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendHeartbeatReply.Merge(m, src)
}
func (m *SendHeartbeatReply) XXX_Size() int {
	return xxx_messageInfo_SendHeartbeatReply.Size(m)
}
func (m *SendHeartbeatReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SendHeartbeatReply.DiscardUnknown(m)
}

var xxx_messageInfo_SendHeartbeatReply proto.InternalMessageInfo

func (m *SendHeartbeatReply) GetNextAction() uint64 {
	if m != nil {
		return m.NextAction
	}
	return 0
}

func (m *SendHeartbeatReply) GetActionParameters() *ActionParameters {
	if m != nil {
		return m.ActionParameters
	}
	return nil
}

type ActionParameters struct {
	Nonce                uint64        `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ClientConfig         *ClientConfig `protobuf:"bytes,2,opt,name=clientConfig,proto3" json:"clientConfig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ActionParameters) Reset()         { *m = ActionParameters{} }
func (m *ActionParameters) String() string { return proto.CompactTextString(m) }
func (*ActionParameters) ProtoMessage()    {}
func (*ActionParameters) Descriptor() ([]byte, []int) {
	return fileDescriptor_69f58a67dc46da5a, []int{13}
}

func (m *ActionParameters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionParameters.Unmarshal(m, b)
}
func (m *ActionParameters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionParameters.Marshal(b, m, deterministic)
}
func (m *ActionParameters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionParameters.Merge(m, src)
}
func (m *ActionParameters) XXX_Size() int {
	return xxx_messageInfo_ActionParameters.Size(m)
}
func (m *ActionParameters) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionParameters.DiscardUnknown(m)
}

var xxx_messageInfo_ActionParameters proto.InternalMessageInfo

func (m *ActionParameters) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *ActionParameters) GetClientConfig() *ClientConfig {
	if m != nil {
		return m.ClientConfig
	}
	return nil
}

type SendReportRequest struct {
	ClientId             int64        `protobuf:"varint,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	TrustReport          *TrustReport `protobuf:"bytes,2,opt,name=trustReport,proto3" json:"trustReport,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SendReportRequest) Reset()         { *m = SendReportRequest{} }
func (m *SendReportRequest) String() string { return proto.CompactTextString(m) }
func (*SendReportRequest) ProtoMessage()    {}
func (*SendReportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_69f58a67dc46da5a, []int{14}
}

func (m *SendReportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendReportRequest.Unmarshal(m, b)
}
func (m *SendReportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendReportRequest.Marshal(b, m, deterministic)
}
func (m *SendReportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendReportRequest.Merge(m, src)
}
func (m *SendReportRequest) XXX_Size() int {
	return xxx_messageInfo_SendReportRequest.Size(m)
}
func (m *SendReportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendReportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendReportRequest proto.InternalMessageInfo

func (m *SendReportRequest) GetClientId() int64 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

func (m *SendReportRequest) GetTrustReport() *TrustReport {
	if m != nil {
		return m.TrustReport
	}
	return nil
}

type TrustReport struct {
	PcrInfo              *PcrInfo    `protobuf:"bytes,1,opt,name=pcrInfo,proto3" json:"pcrInfo,omitempty"`
	Manifest             []*Manifest `protobuf:"bytes,2,rep,name=manifest,proto3" json:"manifest,omitempty"`
	ClientId             int64       `protobuf:"varint,3,opt,name=clientId,proto3" json:"clientId,omitempty"`
	ClientInfo           *ClientInfo `protobuf:"bytes,4,opt,name=clientInfo,proto3" json:"clientInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TrustReport) Reset()         { *m = TrustReport{} }
func (m *TrustReport) String() string { return proto.CompactTextString(m) }
func (*TrustReport) ProtoMessage()    {}
func (*TrustReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_69f58a67dc46da5a, []int{15}
}

func (m *TrustReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrustReport.Unmarshal(m, b)
}
func (m *TrustReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrustReport.Marshal(b, m, deterministic)
}
func (m *TrustReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrustReport.Merge(m, src)
}
func (m *TrustReport) XXX_Size() int {
	return xxx_messageInfo_TrustReport.Size(m)
}
func (m *TrustReport) XXX_DiscardUnknown() {
	xxx_messageInfo_TrustReport.DiscardUnknown(m)
}

var xxx_messageInfo_TrustReport proto.InternalMessageInfo

func (m *TrustReport) GetPcrInfo() *PcrInfo {
	if m != nil {
		return m.PcrInfo
	}
	return nil
}

func (m *TrustReport) GetManifest() []*Manifest {
	if m != nil {
		return m.Manifest
	}
	return nil
}

func (m *TrustReport) GetClientId() int64 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

func (m *TrustReport) GetClientInfo() *ClientInfo {
	if m != nil {
		return m.ClientInfo
	}
	return nil
}

type PcrInfo struct {
	PcrValues            map[int32]string `protobuf:"bytes,1,rep,name=pcrValues,proto3" json:"pcrValues,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	PcrQuote             *PcrQuote        `protobuf:"bytes,2,opt,name=pcrQuote,proto3" json:"pcrQuote,omitempty"`
	Algorithm            string           `protobuf:"bytes,3,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PcrInfo) Reset()         { *m = PcrInfo{} }
func (m *PcrInfo) String() string { return proto.CompactTextString(m) }
func (*PcrInfo) ProtoMessage()    {}
func (*PcrInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_69f58a67dc46da5a, []int{16}
}

func (m *PcrInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PcrInfo.Unmarshal(m, b)
}
func (m *PcrInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PcrInfo.Marshal(b, m, deterministic)
}
func (m *PcrInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PcrInfo.Merge(m, src)
}
func (m *PcrInfo) XXX_Size() int {
	return xxx_messageInfo_PcrInfo.Size(m)
}
func (m *PcrInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PcrInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PcrInfo proto.InternalMessageInfo

func (m *PcrInfo) GetPcrValues() map[int32]string {
	if m != nil {
		return m.PcrValues
	}
	return nil
}

func (m *PcrInfo) GetPcrQuote() *PcrQuote {
	if m != nil {
		return m.PcrQuote
	}
	return nil
}

func (m *PcrInfo) GetAlgorithm() string {
	if m != nil {
		return m.Algorithm
	}
	return ""
}

type PcrQuote struct {
	Quoted               []byte   `protobuf:"bytes,1,opt,name=quoted,proto3" json:"quoted,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PcrQuote) Reset()         { *m = PcrQuote{} }
func (m *PcrQuote) String() string { return proto.CompactTextString(m) }
func (*PcrQuote) ProtoMessage()    {}
func (*PcrQuote) Descriptor() ([]byte, []int) {
	return fileDescriptor_69f58a67dc46da5a, []int{17}
}

func (m *PcrQuote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PcrQuote.Unmarshal(m, b)
}
func (m *PcrQuote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PcrQuote.Marshal(b, m, deterministic)
}
func (m *PcrQuote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PcrQuote.Merge(m, src)
}
func (m *PcrQuote) XXX_Size() int {
	return xxx_messageInfo_PcrQuote.Size(m)
}
func (m *PcrQuote) XXX_DiscardUnknown() {
	xxx_messageInfo_PcrQuote.DiscardUnknown(m)
}

var xxx_messageInfo_PcrQuote proto.InternalMessageInfo

func (m *PcrQuote) GetQuoted() []byte {
	if m != nil {
		return m.Quoted
	}
	return nil
}

func (m *PcrQuote) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Manifest struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Item                 []byte   `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Manifest) Reset()         { *m = Manifest{} }
func (m *Manifest) String() string { return proto.CompactTextString(m) }
func (*Manifest) ProtoMessage()    {}
func (*Manifest) Descriptor() ([]byte, []int) {
	return fileDescriptor_69f58a67dc46da5a, []int{18}
}

func (m *Manifest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Manifest.Unmarshal(m, b)
}
func (m *Manifest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Manifest.Marshal(b, m, deterministic)
}
func (m *Manifest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Manifest.Merge(m, src)
}
func (m *Manifest) XXX_Size() int {
	return xxx_messageInfo_Manifest.Size(m)
}
func (m *Manifest) XXX_DiscardUnknown() {
	xxx_messageInfo_Manifest.DiscardUnknown(m)
}

var xxx_messageInfo_Manifest proto.InternalMessageInfo

func (m *Manifest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Manifest) GetItem() []byte {
	if m != nil {
		return m.Item
	}
	return nil
}

type SendReportReply struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendReportReply) Reset()         { *m = SendReportReply{} }
func (m *SendReportReply) String() string { return proto.CompactTextString(m) }
func (*SendReportReply) ProtoMessage()    {}
func (*SendReportReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_69f58a67dc46da5a, []int{19}
}

func (m *SendReportReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendReportReply.Unmarshal(m, b)
}
func (m *SendReportReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendReportReply.Marshal(b, m, deterministic)
}
func (m *SendReportReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendReportReply.Merge(m, src)
}
func (m *SendReportReply) XXX_Size() int {
	return xxx_messageInfo_SendReportReply.Size(m)
}
func (m *SendReportReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SendReportReply.DiscardUnknown(m)
}

var xxx_messageInfo_SendReportReply proto.InternalMessageInfo

func (m *SendReportReply) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func init() {
	proto.RegisterType((*CreateIKCertRequest)(nil), "CreateIKCertRequest")
	proto.RegisterType((*CreateIKCertReply)(nil), "CreateIKCertReply")
	proto.RegisterType((*CertEncrypted)(nil), "CertEncrypted")
	proto.RegisterType((*Challenge)(nil), "Challenge")
	proto.RegisterType((*RegisterClientRequest)(nil), "RegisterClientRequest")
	proto.RegisterType((*Cert)(nil), "Cert")
	proto.RegisterType((*ClientInfo)(nil), "ClientInfo")
	proto.RegisterType((*RegisterClientReply)(nil), "RegisterClientReply")
	proto.RegisterType((*ClientConfig)(nil), "ClientConfig")
	proto.RegisterType((*UnregisterClientRequest)(nil), "UnregisterClientRequest")
	proto.RegisterType((*UnregisterClientReply)(nil), "UnregisterClientReply")
	proto.RegisterType((*SendHeartbeatRequest)(nil), "SendHeartbeatRequest")
	proto.RegisterType((*SendHeartbeatReply)(nil), "SendHeartbeatReply")
	proto.RegisterType((*ActionParameters)(nil), "ActionParameters")
	proto.RegisterType((*SendReportRequest)(nil), "SendReportRequest")
	proto.RegisterType((*TrustReport)(nil), "TrustReport")
	proto.RegisterType((*PcrInfo)(nil), "PcrInfo")
	proto.RegisterMapType((map[int32]string)(nil), "PcrInfo.PcrValuesEntry")
	proto.RegisterType((*PcrQuote)(nil), "PcrQuote")
	proto.RegisterType((*Manifest)(nil), "Manifest")
	proto.RegisterType((*SendReportReply)(nil), "SendReportReply")
}

func init() { proto.RegisterFile("clientapi/api.proto", fileDescriptor_69f58a67dc46da5a) }

var fileDescriptor_69f58a67dc46da5a = []byte{
	// 899 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xef, 0x6e, 0x23, 0x35,
	0x10, 0xcf, 0xbf, 0xf6, 0x92, 0x49, 0xda, 0x4b, 0xdd, 0xb4, 0x17, 0x45, 0xe8, 0x54, 0x59, 0x42,
	0x0a, 0xe2, 0xe4, 0x40, 0xe0, 0x24, 0x38, 0x38, 0xe9, 0x7a, 0xe1, 0x10, 0x11, 0x02, 0x15, 0x17,
	0xfa, 0x81, 0x7e, 0x40, 0xce, 0x66, 0x9a, 0xae, 0xb2, 0xf1, 0xee, 0x79, 0xbd, 0x88, 0x3c, 0x08,
	0x0f, 0xc0, 0x9b, 0x20, 0xf1, 0x62, 0xc8, 0x5e, 0x67, 0xb3, 0xbb, 0x09, 0x55, 0xc5, 0xa7, 0xcc,
	0xfc, 0xe6, 0xef, 0xce, 0xd8, 0x3f, 0x07, 0x4e, 0xbd, 0xc0, 0x47, 0xa9, 0x45, 0xe4, 0x8f, 0x44,
	0xe4, 0xb3, 0x48, 0x85, 0x3a, 0xa4, 0xb7, 0x70, 0x3a, 0x51, 0x28, 0x34, 0x4e, 0xbf, 0x9f, 0xa0,
	0xd2, 0x1c, 0xdf, 0x27, 0x18, 0x6b, 0x72, 0x0e, 0x87, 0xb8, 0x34, 0x40, 0xbf, 0x7a, 0x51, 0x1d,
	0xb6, 0xb8, 0xd3, 0x48, 0x0f, 0x0e, 0xfc, 0xe5, 0x55, 0x32, 0xeb, 0xd7, 0x2c, 0x9c, 0x2a, 0xc6,
	0xdb, 0x5f, 0xfe, 0x28, 0x56, 0xd8, 0xaf, 0x5f, 0x54, 0x87, 0x1d, 0xee, 0x34, 0x1a, 0xc2, 0x49,
	0x31, 0x79, 0x14, 0xac, 0xc9, 0x27, 0xd0, 0xf6, 0xbd, 0x77, 0xd2, 0x53, 0xeb, 0x48, 0xe3, 0xdc,
	0xe6, 0x6f, 0x8f, 0x8f, 0x99, 0x71, 0xc8, 0x50, 0x9e, 0x77, 0x21, 0x43, 0x68, 0x79, 0xf7, 0x22,
	0x08, 0x50, 0x2e, 0xd0, 0x16, 0x6e, 0x8f, 0x81, 0x4d, 0x36, 0x08, 0xdf, 0x1a, 0xe9, 0x25, 0x1c,
	0x15, 0xf2, 0x90, 0x0b, 0x68, 0x67, 0xca, 0x74, 0x62, 0x8b, 0x75, 0x78, 0x1e, 0x22, 0xc7, 0x50,
	0x9b, 0xde, 0xd8, 0xac, 0x1d, 0x5e, 0x9b, 0xde, 0xd0, 0x3f, 0xab, 0xd0, 0xca, 0x72, 0x93, 0x01,
	0x34, 0x27, 0x0a, 0xe7, 0x6f, 0x83, 0x70, 0xe6, 0x82, 0x33, 0x9d, 0x0c, 0xe1, 0x69, 0x96, 0xe8,
	0x1a, 0x3d, 0x85, 0xda, 0xa5, 0x29, 0xc3, 0xe4, 0x39, 0x80, 0x83, 0x2e, 0x83, 0x85, 0x9d, 0x51,
	0x8b, 0xe7, 0x10, 0x42, 0xa1, 0xe3, 0xb4, 0x2b, 0xa1, 0xc4, 0xaa, 0xdf, 0xb0, 0x69, 0x0a, 0x18,
	0xbd, 0x85, 0x33, 0x8e, 0x0b, 0x3f, 0xd6, 0xa8, 0x26, 0x76, 0x8f, 0x9b, 0x55, 0x9d, 0x41, 0xcd,
	0xf7, 0xdc, 0x18, 0x0f, 0xec, 0x18, 0x79, 0xcd, 0xf7, 0xc8, 0xc7, 0x00, 0xe9, 0xbe, 0xa7, 0xf2,
	0x2e, 0x74, 0x53, 0x6b, 0xb3, 0x49, 0x06, 0xf1, 0x9c, 0x99, 0x0e, 0xa0, 0x61, 0xd7, 0x4b, 0xa0,
	0xe1, 0x6d, 0x96, 0xde, 0xe1, 0x56, 0xa6, 0x2f, 0x00, 0xb6, 0x51, 0xe6, 0x53, 0x72, 0x69, 0xd3,
	0xc3, 0x91, 0xcf, 0x34, 0x87, 0xd3, 0x72, 0x9b, 0x66, 0xe9, 0x03, 0x68, 0x3a, 0xa7, 0x74, 0xe3,
	0x75, 0x9e, 0xe9, 0xe4, 0x53, 0xe8, 0xa4, 0xf2, 0x24, 0x94, 0x77, 0xfe, 0xc2, 0xf5, 0x7a, 0xe4,
	0x7a, 0x4d, 0x41, 0x5e, 0x70, 0xa1, 0x11, 0x74, 0xf2, 0x56, 0xf2, 0x02, 0x4e, 0xee, 0x67, 0xdf,
	0x24, 0x4a, 0x68, 0x3f, 0x94, 0xd7, 0xe8, 0x85, 0x72, 0x1e, 0xbb, 0x3a, 0xbb, 0x06, 0x32, 0x86,
	0x9e, 0x56, 0x49, 0xac, 0xcb, 0x01, 0x35, 0x1b, 0xb0, 0xd7, 0x46, 0x5f, 0xc2, 0xb3, 0x5f, 0xa4,
	0xda, 0xbb, 0x80, 0x07, 0xbe, 0x8d, 0x8e, 0xe0, 0x6c, 0x37, 0xcc, 0x0c, 0xe4, 0x1c, 0x0e, 0x15,
	0xc6, 0x49, 0x90, 0xce, 0xba, 0xc9, 0x9d, 0x46, 0xc7, 0xd0, 0xbb, 0x46, 0x39, 0xff, 0x0e, 0x85,
	0xd2, 0x33, 0x14, 0x8f, 0x2a, 0x12, 0x03, 0x29, 0xc5, 0x98, 0x0a, 0xcf, 0x01, 0x24, 0xfe, 0xa1,
	0x2f, 0x3d, 0xf3, 0x19, 0x36, 0xa6, 0xc1, 0x73, 0x08, 0x79, 0x0d, 0x5d, 0x61, 0x25, 0x7b, 0xbe,
	0x50, 0xa3, 0x8a, 0xdd, 0xe8, 0x4f, 0xd8, 0x65, 0xc9, 0xc0, 0x77, 0x5c, 0xe9, 0x2d, 0x74, 0xcb,
	0x5e, 0x86, 0x1d, 0x64, 0x28, 0x3d, 0x74, 0xd5, 0x52, 0xe5, 0xff, 0xec, 0xf7, 0x37, 0x38, 0x31,
	0x5f, 0xc4, 0x31, 0x0a, 0xd5, 0x63, 0x46, 0x40, 0x18, 0xb4, 0xed, 0xda, 0xd2, 0x08, 0x57, 0xa2,
	0xc3, 0x7e, 0xde, 0x62, 0x3c, 0xef, 0x40, 0xff, 0xaa, 0x42, 0x3b, 0x67, 0x24, 0x14, 0x9e, 0x44,
	0x9e, 0xca, 0xce, 0x74, 0x7b, 0xdc, 0x64, 0x57, 0xa9, 0xce, 0x37, 0x06, 0xf2, 0x21, 0x34, 0x57,
	0x42, 0xfa, 0x77, 0x18, 0x9b, 0x02, 0xf5, 0x61, 0x7b, 0xdc, 0x62, 0x3f, 0x38, 0x80, 0x67, 0xa6,
	0x42, 0x9b, 0xf5, 0x52, 0x9b, 0xc5, 0x4b, 0xd9, 0x78, 0xf8, 0x52, 0xfe, 0x53, 0x85, 0x27, 0xae,
	0x09, 0xf2, 0x12, 0x5a, 0x91, 0xa7, 0x6e, 0x44, 0x90, 0xa0, 0x39, 0xd8, 0xa6, 0xf8, 0xb3, 0x4d,
	0x87, 0xe6, 0x37, 0xb5, 0xbc, 0x93, 0x5a, 0xad, 0xf9, 0xd6, 0xd3, 0xb4, 0x1c, 0x79, 0xea, 0xa7,
	0x24, 0xd4, 0x1b, 0xe2, 0x6c, 0x19, 0x6f, 0x0b, 0xf0, 0xcc, 0x44, 0x3e, 0x80, 0x96, 0x08, 0x16,
	0xa1, 0xf2, 0xf5, 0xfd, 0xca, 0xd1, 0xd3, 0x16, 0x18, 0x7c, 0x0d, 0xc7, 0xc5, 0x0a, 0xa4, 0x0b,
	0xf5, 0x25, 0xae, 0xed, 0xa4, 0x0e, 0xb8, 0x11, 0xcd, 0xe6, 0x7f, 0x37, 0x0e, 0x9b, 0x77, 0xc1,
	0x2a, 0xaf, 0x6a, 0x5f, 0x54, 0xe9, 0x1b, 0x68, 0x6e, 0x2a, 0x9a, 0x43, 0xff, 0xde, 0x08, 0x73,
	0x47, 0x30, 0x4e, 0x33, 0xf5, 0x63, 0x7f, 0x21, 0x85, 0x4e, 0x14, 0x3a, 0x0e, 0xdd, 0x02, 0x74,
	0x0c, 0xcd, 0xcd, 0x98, 0x0d, 0x41, 0xe9, 0x75, 0x84, 0x8e, 0x78, 0xac, 0x6c, 0x30, 0x5f, 0xe3,
	0xca, 0x05, 0x5a, 0x99, 0x7e, 0x04, 0x4f, 0xf3, 0x07, 0xe8, 0x81, 0x1b, 0x37, 0xfe, 0xbb, 0x06,
	0x75, 0x2e, 0x62, 0xf2, 0x0a, 0x3a, 0xf9, 0xc7, 0x8a, 0xf4, 0xd8, 0x9e, 0x87, 0x71, 0x40, 0xd8,
	0xce, 0x8b, 0x46, 0x2b, 0xe4, 0x0d, 0x1c, 0x17, 0x59, 0x8f, 0x9c, 0xb3, 0xbd, 0x6c, 0x3d, 0xe8,
	0xb1, 0x3d, 0xf4, 0x48, 0x2b, 0xe4, 0x5b, 0xe8, 0x96, 0x89, 0x82, 0xf4, 0xd9, 0x7f, 0x50, 0xce,
	0xe0, 0x9c, 0xed, 0x65, 0x15, 0x5a, 0x21, 0xaf, 0xe1, 0xa8, 0xc0, 0x05, 0xe4, 0x8c, 0xed, 0xe3,
	0x93, 0xc1, 0x29, 0xdb, 0xa5, 0x0c, 0x5a, 0x21, 0x9f, 0x03, 0x6c, 0xe7, 0x46, 0x08, 0xdb, 0xb9,
	0x85, 0x83, 0x2e, 0x2b, 0x0d, 0x96, 0x56, 0xde, 0x7e, 0xf5, 0xeb, 0x97, 0x0b, 0x5f, 0x23, 0x32,
	0x2f, 0x5c, 0x8d, 0xc2, 0x08, 0x25, 0x26, 0x01, 0xaa, 0xd1, 0x32, 0x91, 0x11, 0xca, 0x45, 0x8c,
	0x5e, 0x30, 0x12, 0x5a, 0x63, 0xac, 0x2d, 0xa5, 0x8e, 0x94, 0x88, 0x47, 0xd9, 0x7f, 0x91, 0xd9,
	0xa1, 0xfd, 0x23, 0xf2, 0xd9, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd8, 0xf8, 0x90, 0x9b, 0x9f,
	0x08, 0x00, 0x00,
}
