// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: clientapi/api.proto

package clientapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAKCertRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Akcert []byte `protobuf:"bytes,1,opt,name=akcert,proto3" json:"akcert,omitempty"`
	Dvcert []byte `protobuf:"bytes,2,opt,name=dvcert,proto3" json:"dvcert,omitempty"`
}

func (x *GetAKCertRequest) Reset() {
	*x = GetAKCertRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientapi_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAKCertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAKCertRequest) ProtoMessage() {}

func (x *GetAKCertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clientapi_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAKCertRequest.ProtoReflect.Descriptor instead.
func (*GetAKCertRequest) Descriptor() ([]byte, []int) {
	return file_clientapi_api_proto_rawDescGZIP(), []int{0}
}

func (x *GetAKCertRequest) GetAkcert() []byte {
	if x != nil {
		return x.Akcert
	}
	return nil
}

func (x *GetAKCertRequest) GetDvcert() []byte {
	if x != nil {
		return x.Dvcert
	}
	return nil
}

type GetAKCertReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Akcert []byte `protobuf:"bytes,1,opt,name=akcert,proto3" json:"akcert,omitempty"`
}

func (x *GetAKCertReply) Reset() {
	*x = GetAKCertReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientapi_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAKCertReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAKCertReply) ProtoMessage() {}

func (x *GetAKCertReply) ProtoReflect() protoreflect.Message {
	mi := &file_clientapi_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAKCertReply.ProtoReflect.Descriptor instead.
func (*GetAKCertReply) Descriptor() ([]byte, []int) {
	return file_clientapi_api_proto_rawDescGZIP(), []int{1}
}

func (x *GetAKCertReply) GetAkcert() []byte {
	if x != nil {
		return x.Akcert
	}
	return nil
}

type RegisterClientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Clientinfo string `protobuf:"bytes,1,opt,name=clientinfo,proto3" json:"clientinfo,omitempty"`
	Dvcert     []byte `protobuf:"bytes,2,opt,name=dvcert,proto3" json:"dvcert,omitempty"`
}

func (x *RegisterClientRequest) Reset() {
	*x = RegisterClientRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientapi_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterClientRequest) ProtoMessage() {}

func (x *RegisterClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clientapi_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterClientRequest.ProtoReflect.Descriptor instead.
func (*RegisterClientRequest) Descriptor() ([]byte, []int) {
	return file_clientapi_api_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterClientRequest) GetClientinfo() string {
	if x != nil {
		return x.Clientinfo
	}
	return ""
}

func (x *RegisterClientRequest) GetDvcert() []byte {
	if x != nil {
		return x.Dvcert
	}
	return nil
}

type RegisterClientReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Clientid int64 `protobuf:"varint,1,opt,name=clientid,proto3" json:"clientid,omitempty"`
}

func (x *RegisterClientReply) Reset() {
	*x = RegisterClientReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientapi_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterClientReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterClientReply) ProtoMessage() {}

func (x *RegisterClientReply) ProtoReflect() protoreflect.Message {
	mi := &file_clientapi_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterClientReply.ProtoReflect.Descriptor instead.
func (*RegisterClientReply) Descriptor() ([]byte, []int) {
	return file_clientapi_api_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterClientReply) GetClientid() int64 {
	if x != nil {
		return x.Clientid
	}
	return 0
}

var File_clientapi_api_proto protoreflect.FileDescriptor

var file_clientapi_api_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x42, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x4b, 0x43, 0x65,
	0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6b, 0x63,
	0x65, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x61, 0x6b, 0x63, 0x65, 0x72,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x76, 0x63, 0x65, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x06, 0x64, 0x76, 0x63, 0x65, 0x72, 0x74, 0x22, 0x28, 0x0a, 0x0e, 0x47, 0x65, 0x74,
	0x41, 0x4b, 0x43, 0x65, 0x72, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x6b, 0x63, 0x65, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x61, 0x6b, 0x63,
	0x65, 0x72, 0x74, 0x22, 0x4f, 0x0a, 0x15, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06,
	0x64, 0x76, 0x63, 0x65, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x64, 0x76,
	0x63, 0x65, 0x72, 0x74, 0x22, 0x31, 0x0a, 0x13, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x69, 0x64, 0x32, 0x7a, 0x0a, 0x03, 0x54, 0x61, 0x73, 0x12, 0x31,
	0x0a, 0x09, 0x47, 0x65, 0x74, 0x41, 0x4b, 0x43, 0x65, 0x72, 0x74, 0x12, 0x11, 0x2e, 0x47, 0x65,
	0x74, 0x41, 0x4b, 0x43, 0x65, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f,
	0x2e, 0x47, 0x65, 0x74, 0x41, 0x4b, 0x43, 0x65, 0x72, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x00, 0x12, 0x40, 0x0a, 0x0e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x12, 0x16, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x65, 0x65, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x65, 0x75, 0x6c, 0x65, 0x72, 0x2f, 0x6b, 0x75, 0x6e, 0x70, 0x65,
	0x6e, 0x67, 0x73, 0x65, 0x63, 0x6c, 0x2f, 0x61, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2f, 0x74, 0x61, 0x73, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x61, 0x70, 0x69,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_clientapi_api_proto_rawDescOnce sync.Once
	file_clientapi_api_proto_rawDescData = file_clientapi_api_proto_rawDesc
)

func file_clientapi_api_proto_rawDescGZIP() []byte {
	file_clientapi_api_proto_rawDescOnce.Do(func() {
		file_clientapi_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_clientapi_api_proto_rawDescData)
	})
	return file_clientapi_api_proto_rawDescData
}

var file_clientapi_api_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_clientapi_api_proto_goTypes = []interface{}{
	(*GetAKCertRequest)(nil),      // 0: GetAKCertRequest
	(*GetAKCertReply)(nil),        // 1: GetAKCertReply
	(*RegisterClientRequest)(nil), // 2: RegisterClientRequest
	(*RegisterClientReply)(nil),   // 3: RegisterClientReply
}
var file_clientapi_api_proto_depIdxs = []int32{
	0, // 0: Tas.GetAKCert:input_type -> GetAKCertRequest
	2, // 1: Tas.RegisterClient:input_type -> RegisterClientRequest
	1, // 2: Tas.GetAKCert:output_type -> GetAKCertReply
	3, // 3: Tas.RegisterClient:output_type -> RegisterClientReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_clientapi_api_proto_init() }
func file_clientapi_api_proto_init() {
	if File_clientapi_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_clientapi_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAKCertRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientapi_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAKCertReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientapi_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterClientRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientapi_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterClientReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_clientapi_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clientapi_api_proto_goTypes,
		DependencyIndexes: file_clientapi_api_proto_depIdxs,
		MessageInfos:      file_clientapi_api_proto_msgTypes,
	}.Build()
	File_clientapi_api_proto = out.File
	file_clientapi_api_proto_rawDesc = nil
	file_clientapi_api_proto_goTypes = nil
	file_clientapi_api_proto_depIdxs = nil
}
