// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: clientapi/api.proto

package clientapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TasClient is the client API for Tas service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TasClient interface {
	GetAKCert(ctx context.Context, in *GetAKCertRequest, opts ...grpc.CallOption) (*GetAKCertReply, error)
}

type tasClient struct {
	cc grpc.ClientConnInterface
}

func NewTasClient(cc grpc.ClientConnInterface) TasClient {
	return &tasClient{cc}
}

func (c *tasClient) GetAKCert(ctx context.Context, in *GetAKCertRequest, opts ...grpc.CallOption) (*GetAKCertReply, error) {
	out := new(GetAKCertReply)
	err := c.cc.Invoke(ctx, "/Tas/GetAKCert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TasServer is the server API for Tas service.
// All implementations must embed UnimplementedTasServer
// for forward compatibility
type TasServer interface {
	GetAKCert(context.Context, *GetAKCertRequest) (*GetAKCertReply, error)
	mustEmbedUnimplementedTasServer()
}

// UnimplementedTasServer must be embedded to have forward compatible implementations.
type UnimplementedTasServer struct {
}

func (UnimplementedTasServer) GetAKCert(context.Context, *GetAKCertRequest) (*GetAKCertReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAKCert not implemented")
}
func (UnimplementedTasServer) mustEmbedUnimplementedTasServer() {}

// UnsafeTasServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TasServer will
// result in compilation errors.
type UnsafeTasServer interface {
	mustEmbedUnimplementedTasServer()
}

func RegisterTasServer(s grpc.ServiceRegistrar, srv TasServer) {
	s.RegisterService(&Tas_ServiceDesc, srv)
}

func _Tas_GetAKCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAKCertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TasServer).GetAKCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Tas/GetAKCert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TasServer).GetAKCert(ctx, req.(*GetAKCertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Tas_ServiceDesc is the grpc.ServiceDesc for Tas service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tas_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Tas",
	HandlerType: (*TasServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAKCert",
			Handler:    _Tas_GetAKCert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clientapi/api.proto",
}
