/*
kunpengsecl licensed under the Mulan PSL v2.
You can use this software according to the terms and conditions of
the Mulan PSL v2. You may obtain a copy of Mulan PSL v2 at:
    http://license.coscl.org.cn/MulanPSL2
THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
See the Mulan PSL v2 for more details.

Author: leezhenxiang
Create: 2022-11-04
Description: initialize module in kta.
	1. 2022-11-04	leezhenxiang
		define the structures.
    2. 2022-11-18   waterh2o
        redefine some interface
*/

#include <kta_common.h>

// TEE_Result GenerateKeyPair(uint32_t keytype, uint32_t keysize, void *pubkey, void *privkey) {
//     //todo: generate a pair of key according to keytype and keysize

//     //input: keytype, keysize
//     //output: pubkey, privkey

//     /*
//     TEE_TYPE_RSA_KEYPAIR        = 0xA1000030,
//     TEE_TYPE_DSA_KEYPAIR        = 0xA1000031,
//     TEE_TYPE_DH_KEYPAIR         = 0xA1000032,
//     TEE_TYPE_ECDSA_KEYPAIR      = 0xA1000041,
//     TEE_TYPE_ECDH_KEYPAIR       = 0xA1000042,
//     TEE_TYPE_ED25519_KEYPAIR    = 0xA1000043,
//     TEE_TYPE_X25519_KEYPAIR     = 0xA1000044,
//     TEE_TYPE_SM2_DSA_KEYPAIR    = 0xA1000045,
//     TEE_TYPE_SM2_KEP_KEYPAIR    = 0xA1000046,
//     TEE_TYPE_SM2_PKE_KEYPAIR    = 0xA1000047,
//     */
// }

// TEE_Result SignPubKey(void *pubkey, void *signedpubkey) {
//     //todo: sign the public key generated by function GenerateKeyPair with TEE key

//     //input: pubkey
//     //output: signedpubkey
// }

TEE_Result KTAInitialize(void *teepubkey, void *signedpubkey, Cache *cache, CmdQueue *cmdqueue) {
    //basic function for calling the above functions

    //output: teepubkey, signedpubkey
}

TEE_Result KTAInitialReply(void *teepubkey, void *signedpubkey, Cache *cache, CmdQueue *cmdqueue) {
    //basic function for calling the above functions

    //output: teepubkey, signedpubkey
}


void saveLocalKey(void *keyname, void *keyvalue, uint32_t keytype) {
    //todo: save a certain kind ok key into the physical media

    //input: keyname, keyvalue, keytype
}

void restoreLocalKey(void *keyname, void *keyvalue, uint32_t keytype) {
    //todo: restore a certain kind of key from the physical media

    //input: keyname
    //output: keyvalue, keytype
}

void initTACache(Cache cache) {
    //todo: initialize a data cache for saving ka info and saving keys

    //output: cache
}

void initCmdCache(CmdQueue *cmdqueue) {
    //todo: initialize a cmd cache

    //output: cmdqueue
}