qcaconfig:
  server: 127.0.0.1:40007
  akserver: 127.0.0.1:40008
  scenario: 0
  nodaaacfile: ./nodaa-ac.crt
  daaacfile: ./daa-ac.crt
  virtual:
    server: 0.0.0.0:90000
    healthcheck: 10  # minute, <0 no health check, max is 7 day
 